name: .NET

on:
  workflow_dispatch:
  push:
    branches: main
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore nunit.xamarin
    - name: Package
      run: dotnet publish nunit.xamarin --no-restore -c Release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: package
        path: nunit.xamarin/bin/Release/*.nupkg
